### ISSUE TITLE
Welcome NEW PERSON

### ISSUE THREAD

**Issue by rross0** [trueroll/onboarding#3]
# Welcome!

We're excited that you chose to come work with TrueRoll. This web page displays a GitHub issue ticket. An issue ticket is a way to track work. As you work through the tasks in this issue, please check off the associated checkboxes.

## Tasks to complete

- [ ] You will need a GitHub account. If you do not already have one, please create an account using your personal email. Upload a photo to your profile. Comment on this issue below so we know your username.
- [ ] Create a GitHub token. It needs the `admin:org > read:org` scope. Store the token in a password manager.

## Working remotely <a name="working_remotely"></a>

TrueRoll is currently a hybrid-remote company. Many of our employees are fully remote, and we expect you to be able to work remotely. Working remotely requires certain fundamental skills that people often overlook. 

- [ ] Make sure you have a comfortable, distraction-free workspace in your home. Working from a coffee shop or a similar location is fine on occasion, but you should expect to work from your home office regularly. 
- [ ] Make sure you have a stable internet connection that clocks at 50 MBs, with a ping of no more than 15 milliseconds. Click [here](https://www.google.com/search?q=internet+speed+test) to find a speed test. 
- [ ] TrueRoll will provide you with a work computer. Please comment on this issue ticket and tag @jtwalsh0 with your preferred operating system (Mac, PC). Please email your address to [Joe Walsh](mailto:joe@trueroll.io) so we can mail you your computer.
- [ ] TrueRoll will reimburse you for expenses specific to establishing your home office. Expensable items include: up to two monitors, a docking station, a mouse, a keyboard, a microphone. Track your expenses - TrueRoll uses Gusto for reimbursements, and you'll be guided through the process of getting reimbursed for authorized expenses during onboarding.

## Background Check
We conduct background checks on all employees who might access TrueRoll data. When you comment on this issue ticket (see [Working remotely](#working_remotely)), TrueRoll will send you a background-check form.
- [ ] Complete the background check form and send to [Joe Walsh](mailto:joe@trueroll.io) before your first day.

## Your first day

We will create a new issue ticket with the items you will need to complete after you start at TrueRoll. We look forward to seeing you (virtually) on your first day!

## Tasks for TrueRoll

- [ ] Order laptop.
- [ ] Create OpenVPN credentials and share securely.
- [ ] Create database credentials and share securely.
- [ ] Add to Gusto.
- [ ] Conduct background check.
